name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build SuperDucker.Shared
        run: dotnet build SuperDucker.Shared/SuperDucker.Shared.csproj -c Release

      - name: Build SuperDucker.App
        run: dotnet build SuperDucker.App/SuperDucker.App.csproj -c Release

      - name: Build SuperDucker.Cli
        run: dotnet build SuperDucker.Cli/SuperDucker.Cli.csproj -c Release
